o Reverted last commit due to
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error uploading site
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:719)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
	at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error uploading site
	at org.apache.maven.plugins.site.AbstractDeployMojo.push(AbstractDeployMojo.java:390)
	at org.apache.maven.plugins.site.AbstractDeployMojo.deploy(AbstractDeployMojo.java:249)
	at org.apache.maven.plugins.site.AbstractDeployMojo.deployTo(AbstractDeployMojo.java:227)
	at org.apache.maven.plugins.site.AbstractDeployMojo.execute(AbstractDeployMojo.java:135)
	at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
	... 17 more
Caused by: org.apache.maven.wagon.TransferFailedException: Error occurred while deploying '/tmp/trunk/target/site' to remote repository: sftp://web.sourceforge.net/home/project-web/jomc/htdocs/jomc/1.2/
	at org.apache.maven.wagon.providers.ssh.jsch.SftpWagon.putDirectory(SftpWagon.java:286)
	at org.apache.maven.plugins.site.AbstractDeployMojo.push(AbstractDeployMojo.java:373)
	... 22 more
Caused by: 4: 
	at com.jcraft.jsch.ChannelSftp.mkdir(ChannelSftp.java:1706)
	at org.apache.maven.wagon.providers.ssh.jsch.SftpWagon.mkdir(SftpWagon.java:204)
	at org.apache.maven.wagon.providers.ssh.jsch.SftpWagon.ftpRecursivePut(SftpWagon.java:300)
	at org.apache.maven.wagon.providers.ssh.jsch.SftpWagon.putDirectory(SftpWagon.java:277)
	... 23 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:558)
	at com.jcraft.jsch.ChannelSftp.remoteAbsolutePath(ChannelSftp.java:2361)
	at com.jcraft.jsch.ChannelSftp.mkdir(ChannelSftp.java:1684)
	... 26 more


git-svn-id: http://svn.jomc.org/svnroot/jomc/jomc/trunk@3450 aee2edba-5628-49ba-b8b8-0e9d4ac63d57